export type Supply = 'mono' | 'bi' | 'tri';
export type ViewMode = 'realistic' | 'schematic' | 'installation' | 'labels';
export type Tool = 'select' | 'wire' | 'pan';
export type Conductor = 'phase' | 'neutral' | 'earth' | 'return';
export type TerminalSide = 'top' | 'bottom' | 'left' | 'right';
export type DeviceMount = 'rail' | 'edge' | 'overlay';
export type EdgeSide = 'top' | 'bottom' | 'left' | 'right';
export type BusOrientation = 'vertical' | 'horizontal';
export type CombSide = 'top' | 'bottom';
export type DeviceVisualModel = 'classic' | 'graphite' | 'two-tone';
export type DpsInput = 'phase' | 'neutral';
export type DpsVisual = 'standard' | 'red';
export type WireTermination = 'tubular' | 'generico' | 'pente' | 'olhal' | 'garfo' | 'pino' | 'sem-terminal';
export type Point = { x: number; y: number };
export type Terminal = { id: string; label: string; side: TerminalSide; index: number; kind: 'L' | 'N' | 'PE' | 'control'; pole?: number; position?: Point };
export type Device = {
  id: string; type: string; label: string; rail: number; slot: number; modules: number;
  poles: number; amperage: number | null; curve: 'B' | 'C' | 'D'; gauge: number | null;
  sensitivity: number; voltage: number; surgeCurrent: number; description: string;
  circuitId: string | null; color: string; terminals: Terminal[];
  mount?: DeviceMount; edgeSide?: EdgeSide; edgeOffset?: number; model?: string; visualModel?: DeviceVisualModel;
  technicalModelId?: string; visualVariant?: string; breakingCapacityKa?: number | null; tag?: string;
  spdInput?: DpsInput; visualRotation?: 0 | 180;
  canvasPosition?: Point;
  orientation?: BusOrientation; busTerminalSide?: TerminalSide; combSide?: CombSide;
};
export type Wire = {
  id: string; sourceComponent: string; sourceTerminal: string;
  targetComponent: string; targetTerminal: string;
  conductorType: Conductor; color: string; gauge: number | null; label: string; path: Point[];
  sourceTermination?: WireTermination; targetTermination?: WireTermination;
  manualPath?: boolean;
};
export type Circuit = {
  id: string; number: number; name: string; phase: string; breakerId: string | null;
  cableGauge: number | null; load: number | null; loadUnit: 'W' | 'A'; voltage: number;
  powerFactor: number; drId: string | null; notes: string; color: string;
};
export type Material = { id: string; name: string; specification: string; quantity: number; unit: string };
export type Project = {
  version: 2; id: string; name: string; client: string; supply: Supply; voltage: number;
  rails: number; modulesPerRail: number; widthMm: number; heightMm: number;
  visualModel: DeviceVisualModel; dpsVisual: DpsVisual;
  devices: Device[]; wires: Wire[]; circuits: Circuit[]; materials: Material[];
  createdAt: string; updatedAt: string;
};
export type CatalogItem = { type: string; name: string; category: string; modules: number; poles: number; description: string; mount?: DeviceMount };
export type Selection = { devices: string[]; wire: string | null };
export type WireOptions = { conductorType: Conductor; color: string; gauge: number | null; termination: WireTermination };
export type WarningSeverity = 'error' | 'warning' | 'info';
export type Warning = { id: string; severity: WarningSeverity; message: string; deviceId?: string; wireId?: string; circuitId?: string };
export type Viewport = { x: number; y: number; zoom: number };
export const PRELIMINARY_NOTICE = 'Configuração visual preliminar. O dimensionamento, proteção, capacidade de condução, curto-circuito, DR, DPS, queda de tensão e demais critérios devem ser verificados por profissional habilitado conforme as normas aplicáveis.';
